# Generated by Django 3.1.5 on 2021-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classproducts',
            name='product_desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classproducts',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classproducts',
            name='product_price',
            field=models.CharField(max_length=50),
        ),
    ]
